# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CartBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, song_id: int=None, album_id: int=None, merch_id: int=None, unidades: int=None):  # noqa: E501
        """CartBody - a model defined in Swagger

        :param song_id: The song_id of this CartBody.  # noqa: E501
        :type song_id: int
        :param album_id: The album_id of this CartBody.  # noqa: E501
        :type album_id: int
        :param merch_id: The merch_id of this CartBody.  # noqa: E501
        :type merch_id: int
        :param unidades: The unidades of this CartBody.  # noqa: E501
        :type unidades: int
        """
        self.swagger_types = {
            'song_id': int,
            'album_id': int,
            'merch_id': int,
            'unidades': int
        }

        self.attribute_map = {
            'song_id': 'songId',
            'album_id': 'albumId',
            'merch_id': 'merchId',
            'unidades': 'unidades'
        }
        self._song_id = song_id
        self._album_id = album_id
        self._merch_id = merch_id
        self._unidades = unidades

    @classmethod
    def from_dict(cls, dikt) -> 'CartBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cart_body of this CartBody.  # noqa: E501
        :rtype: CartBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def song_id(self) -> int:
        """Gets the song_id of this CartBody.

        ID of the song to add.  # noqa: E501

        :return: The song_id of this CartBody.
        :rtype: int
        """
        return self._song_id

    @song_id.setter
    def song_id(self, song_id: int):
        """Sets the song_id of this CartBody.

        ID of the song to add.  # noqa: E501

        :param song_id: The song_id of this CartBody.
        :type song_id: int
        """

        self._song_id = song_id

    @property
    def album_id(self) -> int:
        """Gets the album_id of this CartBody.

        ID of the album to add.  # noqa: E501

        :return: The album_id of this CartBody.
        :rtype: int
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: int):
        """Sets the album_id of this CartBody.

        ID of the album to add.  # noqa: E501

        :param album_id: The album_id of this CartBody.
        :type album_id: int
        """

        self._album_id = album_id

    @property
    def merch_id(self) -> int:
        """Gets the merch_id of this CartBody.

        ID of the merch to add.  # noqa: E501

        :return: The merch_id of this CartBody.
        :rtype: int
        """
        return self._merch_id

    @merch_id.setter
    def merch_id(self, merch_id: int):
        """Sets the merch_id of this CartBody.

        ID of the merch to add.  # noqa: E501

        :param merch_id: The merch_id of this CartBody.
        :type merch_id: int
        """

        self._merch_id = merch_id

    @property
    def unidades(self) -> int:
        """Gets the unidades of this CartBody.

        Quantity of items to add (only if merch)  # noqa: E501

        :return: The unidades of this CartBody.
        :rtype: int
        """
        return self._unidades

    @unidades.setter
    def unidades(self, unidades: int):
        """Sets the unidades of this CartBody.

        Quantity of items to add (only if merch)  # noqa: E501

        :param unidades: The unidades of this CartBody.
        :type unidades: int
        """

        self._unidades = unidades
