# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Artists(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, artist_id: int=None, artistic_name: str=None):  # noqa: E501
        """InlineResponse200Artists - a model defined in Swagger

        :param artist_id: The artist_id of this InlineResponse200Artists.  # noqa: E501
        :type artist_id: int
        :param artistic_name: The artistic_name of this InlineResponse200Artists.  # noqa: E501
        :type artistic_name: str
        """
        self.swagger_types = {
            'artist_id': int,
            'artistic_name': str
        }

        self.attribute_map = {
            'artist_id': 'artistId',
            'artistic_name': 'artisticName'
        }
        self._artist_id = artist_id
        self._artistic_name = artistic_name

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Artists':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_artists of this InlineResponse200Artists.  # noqa: E501
        :rtype: InlineResponse200Artists
        """
        return util.deserialize_model(dikt, cls)

    @property
    def artist_id(self) -> int:
        """Gets the artist_id of this InlineResponse200Artists.


        :return: The artist_id of this InlineResponse200Artists.
        :rtype: int
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: int):
        """Sets the artist_id of this InlineResponse200Artists.


        :param artist_id: The artist_id of this InlineResponse200Artists.
        :type artist_id: int
        """

        self._artist_id = artist_id

    @property
    def artistic_name(self) -> str:
        """Gets the artistic_name of this InlineResponse200Artists.


        :return: The artistic_name of this InlineResponse200Artists.
        :rtype: str
        """
        return self._artistic_name

    @artistic_name.setter
    def artistic_name(self, artistic_name: str):
        """Sets the artistic_name of this InlineResponse200Artists.


        :param artistic_name: The artistic_name of this InlineResponse200Artists.
        :type artistic_name: str
        """

        self._artistic_name = artistic_name
