# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Pagination(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, page: int=None, limit: int=None, total: int=None, total_pages: int=None):  # noqa: E501
        """InlineResponse200Pagination - a model defined in Swagger

        :param page: The page of this InlineResponse200Pagination.  # noqa: E501
        :type page: int
        :param limit: The limit of this InlineResponse200Pagination.  # noqa: E501
        :type limit: int
        :param total: The total of this InlineResponse200Pagination.  # noqa: E501
        :type total: int
        :param total_pages: The total_pages of this InlineResponse200Pagination.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {
            'page': int,
            'limit': int,
            'total': int,
            'total_pages': int
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total': 'total',
            'total_pages': 'totalPages'
        }
        self._page = page
        self._limit = limit
        self._total = total
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_pagination of this InlineResponse200Pagination.  # noqa: E501
        :rtype: InlineResponse200Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this InlineResponse200Pagination.


        :return: The page of this InlineResponse200Pagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this InlineResponse200Pagination.


        :param page: The page of this InlineResponse200Pagination.
        :type page: int
        """

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this InlineResponse200Pagination.


        :return: The limit of this InlineResponse200Pagination.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this InlineResponse200Pagination.


        :param limit: The limit of this InlineResponse200Pagination.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this InlineResponse200Pagination.


        :return: The total of this InlineResponse200Pagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this InlineResponse200Pagination.


        :param total: The total of this InlineResponse200Pagination.
        :type total: int
        """

        self._total = total

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this InlineResponse200Pagination.


        :return: The total_pages of this InlineResponse200Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this InlineResponse200Pagination.


        :param total_pages: The total_pages of this InlineResponse200Pagination.
        :type total_pages: int
        """

        self._total_pages = total_pages
