# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_artists import InlineResponse200Artists  # noqa: F401,E501
from swagger_server.models.inline_response200_genres import InlineResponse200Genres  # noqa: F401,E501
from swagger_server.models.inline_response200_pagination import InlineResponse200Pagination  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[Product]=None, pagination: InlineResponse200Pagination=None, genres: List[InlineResponse200Genres]=None, artists: List[InlineResponse200Artists]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: List[Product]
        :param pagination: The pagination of this InlineResponse200.  # noqa: E501
        :type pagination: InlineResponse200Pagination
        :param genres: The genres of this InlineResponse200.  # noqa: E501
        :type genres: List[InlineResponse200Genres]
        :param artists: The artists of this InlineResponse200.  # noqa: E501
        :type artists: List[InlineResponse200Artists]
        """
        self.swagger_types = {
            'data': List[Product],
            'pagination': InlineResponse200Pagination,
            'genres': List[InlineResponse200Genres],
            'artists': List[InlineResponse200Artists]
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination',
            'genres': 'genres',
            'artists': 'artists'
        }
        self._data = data
        self._pagination = pagination
        self._genres = genres
        self._artists = artists

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Product]:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: List[Product]
        """

        self._data = data

    @property
    def pagination(self) -> InlineResponse200Pagination:
        """Gets the pagination of this InlineResponse200.


        :return: The pagination of this InlineResponse200.
        :rtype: InlineResponse200Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: InlineResponse200Pagination):
        """Sets the pagination of this InlineResponse200.


        :param pagination: The pagination of this InlineResponse200.
        :type pagination: InlineResponse200Pagination
        """

        self._pagination = pagination

    @property
    def genres(self) -> List[InlineResponse200Genres]:
        """Gets the genres of this InlineResponse200.

        Complete catalog of available genres from TyA  # noqa: E501

        :return: The genres of this InlineResponse200.
        :rtype: List[InlineResponse200Genres]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[InlineResponse200Genres]):
        """Sets the genres of this InlineResponse200.

        Complete catalog of available genres from TyA  # noqa: E501

        :param genres: The genres of this InlineResponse200.
        :type genres: List[InlineResponse200Genres]
        """

        self._genres = genres

    @property
    def artists(self) -> List[InlineResponse200Artists]:
        """Gets the artists of this InlineResponse200.

        Complete catalog of available artists from TyA  # noqa: E501

        :return: The artists of this InlineResponse200.
        :rtype: List[InlineResponse200Artists]
        """
        return self._artists

    @artists.setter
    def artists(self, artists: List[InlineResponse200Artists]):
        """Sets the artists of this InlineResponse200.

        Complete catalog of available artists from TyA  # noqa: E501

        :param artists: The artists of this InlineResponse200.
        :type artists: List[InlineResponse200Artists]
        """

        self._artists = artists
